version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus_mm_2026
      POSTGRES_DB: nexus_mm
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus -d nexus_mm"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "16379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  wukongim:
    image: wukongim/wukongim:v2
    ports:
      - "15001:5001"
      - "15100:5100"
      - "15200:5200"
      - "15300:5300"
    environment:
      WK_MODE: debug
    volumes:
      - wkdata:/root/wukongim

  meilisearch:
    image: getmeili/meilisearch:v1.6
    ports:
      - "17700:7700"
    environment:
      MEILI_ENV: development
    volumes:
      - msdata:/meili_data

volumes:
  pgdata:
  wkdata:
  msdata:
